name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Publish to crates.io
      run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: publish
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          ## What's Changed
          
          - Check the [changelog](CHANGELOG.md) for detailed changes
          - View the [documentation](https://docs.rs/soft-canonicalize) for usage examples
          
          **Full Changelog**: https://github.com/DK26/soft-canonicalize-rs/compare/v0.0.1...${{ github.ref_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
